# Generated by Django 4.0.6 on 2022-07-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppagent',
            old_name='surname_name',
            new_name='surname',
        ),
    ]
