# Generated by Django 4.0.6 on 2022-08-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0003_pricingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingmodel',
            name='name',
            field=models.CharField(default='home', max_length=30),
            preserve_default=False,
        ),
    ]
