# Generated by Django 4.0.6 on 2022-09-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0006_alter_discounts_options_discounts_vale_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='DiscountsModel',
        ),
    ]
