# Generated by Django 4.0.6 on 2022-11-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0009_phonemodel_number_of_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
