# Generated by Django 4.0.6 on 2022-11-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac_app', '0010_phonemodel_date_added_phonemodel_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='xxx',
            field=models.CharField(default='kkk', max_length=50),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
